# Generated by Django 4.1.7 on 2023-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='bio',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
    ]
