# Generated by Django 4.1.7 on 2023-03-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnoa', '0002_alter_contact_bio_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contactform',
        ),
    ]
