# Generated by Django 4.1.7 on 2023-03-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnoa', '0003_rename_contact_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='name',
            new_name='myname',
        ),
    ]
