# Generated by Django 4.1.7 on 2023-03-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoa', '0004_rename_name_contactform_myname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='bio',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='myname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
