# Generated by Django 4.1.7 on 2023-03-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoa', '0005_alter_contactform_bio_alter_contactform_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('bio', models.TextField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Contactform',
        ),
    ]
