# Generated by Django 4.1.7 on 2023-03-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoa', '0006_contact_delete_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('bio', models.TextField(max_length=64)),
                ('images', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
